"""empty message

Revision ID: 03edbe4e1776
Revises: b9b19013b3d3
Create Date: 2023-08-31 00:10:02.222868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03edbe4e1776'
down_revision = 'b9b19013b3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('past_orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=True),
    sa.Column('menuItemIDs', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_past_orders_restaurant_id_restaurants'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_past_orders_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
