"""empty message

Revision ID: 14ab3c61c7c1
Revises: ce1dd383b21d
Create Date: 2023-08-30 22:02:48.420659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ab3c61c7c1'
down_revision = 'ce1dd383b21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantities', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.drop_column('quantities')

    # ### end Alembic commands ###
