"""empty message

Revision ID: 7aa12b554689
Revises: a1a5c21ca69a
Create Date: 2023-08-30 17:47:05.870690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa12b554689'
down_revision = 'a1a5c21ca69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
