"""empty message

Revision ID: 9680c00c5eec
Revises: d65ddde46571
Create Date: 2023-08-31 00:55:39.952373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9680c00c5eec'
down_revision = 'd65ddde46571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastorders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pastorders_restaurant_id_restaurants', type_='foreignkey')
        batch_op.drop_constraint('fk_pastorders_user_id_users', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pastorders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_pastorders_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_pastorders_restaurant_id_restaurants', 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###
