"""empty message

Revision ID: 9f55b5794a47
Revises: 57e17081fae1
Create Date: 2023-08-29 22:13:22.964868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f55b5794a47'
down_revision = '57e17081fae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_past_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_menuitems_past_order_id_past_orders'), 'past_orders', ['past_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_menuitems_past_order_id_past_orders'), type_='foreignkey')
        batch_op.drop_column('past_order_id')

    op.drop_table('past_orders')
    # ### end Alembic commands ###
