"""empty message

Revision ID: a1a5c21ca69a
Revises: 9f55b5794a47
Create Date: 2023-08-29 22:17:45.522119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a5c21ca69a'
down_revision = '9f55b5794a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_past_orders_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_past_orders_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
