"""empty message

Revision ID: a3ba098e63d7
Revises: 03edbe4e1776
Create Date: 2023-08-31 00:25:57.643221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ba098e63d7'
down_revision = '03edbe4e1776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('menuItemIDs', sa.String(), nullable=True),
    sa.Column('quantities', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pastorders')
    # ### end Alembic commands ###
