"""empty message

Revision ID: b9b19013b3d3
Revises: 7aa12b554689
Create Date: 2023-08-30 18:06:35.374014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b19013b3d3'
down_revision = '7aa12b554689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.drop_constraint('fk_menuitems_past_order_id_past_orders', type_='foreignkey')
        batch_op.drop_column('past_order_id')

    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menuItemIDs', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.drop_column('menuItemIDs')

    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_menuitems_past_order_id_past_orders', 'past_orders', ['past_order_id'], ['id'])

    # ### end Alembic commands ###
