"""empty message

Revision ID: d9c708038d30
Revises: c32910f27042
Create Date: 2023-08-30 21:53:44.728099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c708038d30'
down_revision = 'c32910f27042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.drop_column('quantities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('past_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantities', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
